update test image from beta

diff --git a/.github/workflows/cb-service-container.yaml b/.github/workflows/cb-service-container.yaml
--- a/.github/workflows/cb-service-container.yaml
+++ b/.github/workflows/cb-service-container.yaml
@@ -13,7 +13,7 @@ jobs:
     steps:
     - name: Update repositories
       run: |
-        apt update || echo "apt-update failed" # && apt -y upgrade 
+        apt update || echo "apt-update failed" # && apt -y upgrade
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
@@ -62,7 +62,7 @@ jobs:
       run: npm test
     services:
       couchbase:
-        image: couchbase:enterprise-7.0.0-beta
+        image: couchbase:enterprise-7.0.0
         ports:
           - 8091:8091
           - 8092:8092
